language: csharp
solution: Durian/Durian.sln.sln
mono: none
dotnet: 2.2.0
install:
 - dotnet restore
script:
 - dotnet build
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
