dist: bionic
language: csharp
mono: none
dotnet: 2.2.105
sudo: false
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true
script:
    - dotnet build ./Durian/Durian.sln -c Release
